language: node_js
node_js:
  - '0.10'
before_install:
  - $PUSH_NOTIFICATION $PUSH_ARGS --data-urlencode 'message=Hi! Travis is here...'
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta3
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
script:
  - make
after_success:
  - $PUSH_NOTIFICATION $PUSH_ARGS --data-urlencode 'message=Deploying...'
  - make publish
  - $PUSH_NOTIFICATION $PUSH_ARGS --data-urlencode 'message=Deployed to Userstyles.org!'
  - make upload
  - $PUSH_NOTIFICATION $PUSH_ARGS --data-urlencode 'message=Uploaded to dark-facebook.appspot.com!'
after_failure:
  - $PUSH_NOTIFICATION $PUSH_ARGS --data-urlencode 'message=Build Failed'
env:
  global:

    # This is the userstyles.org cookie, in encrypted form
    - secure: "pBPWegv7ztZfQZW7xvhXxpC8X7Y8FXV3p5csvQMvCgEeCoa/3whCOWyQnwW4uHYlE37j2bRuyO3t0vEVAQgBAwd2lJFZb4i8fOw/fSIirhlGBgwL8eBVT+dVzrEW1EUwzETRZa/2j5nBn6djrgxw6RBpA+AT+P0gwIGFIxL/3N8="

    # The target style ID
    - DFB2_ID=95359

    # For notification... $PUSH_NOTIFICATION, $PUSH_ARGS
    - secure: "B4vTxg9oswtDi5du2dof3o5DQXNh08pyPFei57jDZwjD14uguY4Vrq8YW60oDFMrvk7OXthes/9T1WJT6K69ZALTdUNymhCaHCbRRgZYGOx765Kv2ruy1afR0JxE46P0mxcYIMpeRYcimixd3mvd//dPFhjTiplWfBEI+UtEJ4E="
    - secure: "IIOFiPlY6TSV3VVHJgmBlxRWt5fp+mxl/3S4yGDvu01gu3Dpgr0M7MbCGgtJ6sH6GAEICx+DQCognGD/wSQK/xBjil/ypPsqtNUPJiJgqpIQfO19qVLDHVLNL8C3L7VPTwhsRToPH5FTRH+slHY9+aYJ4LREALu4ELiTcv4zWtQ="

    # For deployment
    - secure: "M9QSRKgv0bMjRfcCj75bEY/GsGL37KcER23mVWNHLJNVhs6q3tyOxlNt7h7cUseOZXuarVdNGVtD0uw98Kh4UaU+X3hckIIyarSxv60yb09XesojVcOELyHh7wn5WKKEkDQJj2invA8z8u/vId2hcCDvZ0YotxBYZSZX1PvU4nw="

branches:
  only:
    - dfb2
