
composer:
  selector: "._55d0"
  info: |
    The status update box, one that asks you, "what's on your mind?"
  children:
    type:
      selector: "._9lb"
      info: |
        The post type, such as "Update Status", "Add Photos/Video" text.
      children:
        active: { selector: "._519b ._9lb" }
    panel:
      selector: "._2yg"
      info: |
        The composer box that holds the whole composer panel.
    toolbar:
      selector:
        - "._1dsp"
      info: |
        The composer toolbar
      children:
        button-left:
          selector: "._1dsq"
          info: |
            The buttons at the bottom left of the composer toolbar.
            The buttons to "Tag Location" or add a "Feeling".
    toolbar-mar2014(mar2014):
      selector:
        - "._5t_y ._1dsl"
      info: |
        The composer toolbar, in March 2014 redesign of Facebook.
      children:
        separator:
          selector: "& li:after"
        info: |
          The separator between each toolbar item
          (e.g. write post, add photo / video, add question)
        hover-button:
          selector: "._5t_y ._9lb:hover"
    typeahead:
      selector: ".composerTypeahead"
      info: The text box to enter your status.
    border:
      selector: "._50zb"
      info: |
        The border that separates the composer from the rest of the stream posts.
      found: Close friends stream
    share-stage:
      selector: "._4_4e"
      info: |
        The "link preview".
      children:
        inline-edit-link:
          selector:
            - ".UIShareStage a.inline_edit"
        inline-edit-input:
          selector:
            - ".UIShareStage input.inline_edit"
            - ".UIShareStage textarea.inline_edit"